// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UpdateBuildVersion
{
    internal sealed partial class Vsix
    {
        public const string Id = "UpdateBuildVersion.3d2154c1-2ce9-439d-8fa1-af586ab8982d";
        public const string Name = "Update Build Version Extensions";
        public const string Description = @"Update version numbers for the build.";
        public const string Language = "en-US";
        public const string Version = "1.3.2";
        public const string Author = "Justin Braun";
        public const string Tags = "";
    }
}
